version: "3.10"

services:
  twelwe-ai-agents:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
